# Generated by Django 2.0 on 2018-05-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites',
            new_name='Site',
        ),
        migrations.RenameModel(
            old_name='Steps',
            new_name='Step',
        ),
    ]
