# Generated by Django 2.0 on 2018-05-11 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180506_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='sites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.Site'),
        ),
    ]
