# Generated by Django 2.0 on 2018-05-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180510_1121'),
        ('core', '0004_auto_20180511_0431'),
    ]

    operations = [
    ]
