# Generated by Django 2.0 on 2018-05-13 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20180511_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.Project'),
        ),
    ]
