# Generated by Django 2.0 on 2018-05-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180513_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='step',
            name='checklist_de',
        ),
        migrations.RemoveField(
            model_name='step',
            name='checklist_en',
        ),
    ]
