# Generated by Django 2.0 on 2018-05-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180513_1020'),
        ('core', '0007_category_material'),
    ]

    operations = [
    ]
