# Generated by Django 2.0 on 2018-05-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_checklist_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
