# Generated by Django 2.0 on 2018-05-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180514_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='Question',
        ),
        migrations.AddField(
            model_name='checklist',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
