# Generated by Django 2.0 on 2018-05-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180514_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='sites',
            new_name='site',
        ),
    ]
