# Generated by Django 2.0 on 2018-05-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180514_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='language',
        ),
        migrations.AddField(
            model_name='setting',
            name='local_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
