# Generated by Django 2.0 on 2018-05-15 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180514_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.Step'),
        ),
    ]
