# Generated by Django 2.0 on 2018-05-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180515_0532'),
        ('core', '0008_category_project'),
    ]

    operations = [
    ]
