# Generated by Django 2.0 on 2018-05-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20180515_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='education_material',
        ),
        migrations.AddField(
            model_name='material',
            name='checklist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_material', to='core.Checklist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_steps', to='core.Step'),
        ),
    ]
