# Generated by Django 2.0 on 2018-05-15 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180515_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_material', to='core.Checklist'),
        ),
    ]
