# Generated by Django 2.0 on 2018-05-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180515_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='checklist',
        ),
        migrations.AddField(
            model_name='checklist',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_material', to='core.Material'),
        ),
    ]
