# Generated by Django 2.0 on 2018-05-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='report/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='local_language',
            field=models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English')], max_length=2, null=True),
        ),
    ]
