# Generated by Django 2.0 on 2018-05-22 12:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180521_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='site',
            name='longitude',
        ),
        migrations.AddField(
            model_name='site',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='description_de',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
