# Generated by Django 2.0 on 2018-05-23 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180521_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='description_de',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitematerials',
            name='materials',
            field=models.ManyToManyField(related_name='site_materials', to='core.Material'),
        ),
        migrations.AddField(
            model_name='sitematerials',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_site_materials', to='core.Site'),
        ),
    ]
