# Generated by Django 2.0 on 2018-05-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20180522_1209'),
        ('core', '0027_auto_20180523_0321'),
    ]

    operations = [
    ]
