# Generated by Django 2.0 on 2018-05-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20180523_0921'),
        ('core', '0028_merge_20180523_0814'),
    ]

    operations = [
    ]
