# Generated by Django 2.0 on 2018-06-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20180524_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
