# Generated by Django 2.0 on 2018-09-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180918_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsteps',
            name='project',
        ),
        migrations.AddField(
            model_name='constructionsteps',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='construction_steps', to='core.Project'),
        ),
    ]
