# Generated by Django 2.0 on 2018-09-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20180918_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsteps',
            name='project',
        ),
        migrations.AddField(
            model_name='constructionsteps',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_steps', to='core.Project'),
        ),
    ]
