# Generated by Django 2.0 on 2018-09-19 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20180918_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsubsteps',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_substeps', to='core.Project'),
        ),
    ]
