# Generated by Django 2.0 on 2018-09-19 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_constructionsubsteps_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsubsteps',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='constructionsubsteps',
            name='project',
        ),
        migrations.RemoveField(
            model_name='constructionsubsteps',
            name='step',
        ),
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.AddField(
            model_name='material',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='primary_photo',
            field=models.ImageField(blank=True, null=True, upload_to='materials/primary_photo'),
        ),
        migrations.AddField(
            model_name='material',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.ConstructionSteps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesteps',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_steps', to='core.Category'),
        ),
        migrations.DeleteModel(
            name='ConstructionSubSteps',
        ),
    ]
