# Generated by Django 2.0 on 2018-09-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20180919_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsubsteps',
            name='description_de',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='constructionsubsteps',
            name='description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='constructionsubsteps',
            name='title_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='constructionsubsteps',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
