# Generated by Django 2.0 on 2018-09-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20180919_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsubsteps',
            name='bad_photo',
            field=models.ImageField(blank=True, null=True, upload_to='materials/bad_photo'),
        ),
        migrations.AlterField(
            model_name='constructionsubsteps',
            name='good_photo',
            field=models.ImageField(blank=True, null=True, upload_to='materials/good_photo'),
        ),
    ]
