# Generated by Django 2.0 on 2018-09-19 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180919_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.ConstructionSteps'),
        ),
    ]
