# Generated by Django 2.0 on 2018-09-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180919_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesteps',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_steps', to='core.Site'),
        ),
        migrations.AlterField(
            model_name='sitesteps',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_steps', to='core.ConstructionSteps'),
        ),
    ]
