# Generated by Django 2.0 on 2018-09-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_primaryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryphoto',
            name='construction_sub_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_photos', to='core.ConstructionSubSteps'),
        ),
        migrations.AlterField(
            model_name='primaryphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/updated_primary_photo'),
        ),
    ]
