# Generated by Django 2.0 on 2018-09-26 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0047_substepchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstepReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='report/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('substep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.ConstructionSubSteps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
