# Generated by Django 2.0 on 2018-09-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_substepreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substepreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
