# Generated by Django 2.0 on 2018-09-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20180926_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substepchecklist',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.SiteSteps'),
        ),
        migrations.AlterField(
            model_name='substepchecklist',
            name='substep',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.ConstructionSubSteps'),
            preserve_default=False,
        ),
    ]
