# Generated by Django 2.0 on 2018-09-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20180926_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='substepchecklist',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.Site'),
        ),
    ]
