# Generated by Django 2.0 on 2018-09-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_substepchecklist_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='substepreport',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.Site'),
        ),
        migrations.AddField(
            model_name='substepreport',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.SiteSteps'),
        ),
    ]
