# Generated by Django 2.0 on 2018-09-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20180926_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsteps',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='construction_step/'),
        ),
    ]
