# Generated by Django 2.0 on 2018-09-27 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_constructionsteps_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/updated_bad_photo')),
                ('construction_sub_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bad_photos', to='core.ConstructionSubSteps')),
            ],
        ),
        migrations.CreateModel(
            name='GoodPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/updated_good_photo')),
                ('construction_sub_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_photos', to='core.ConstructionSubSteps')),
            ],
        ),
    ]
