# Generated by Django 2.0 on 2018-10-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_buildahousekeypartsofhouse_buildahousemakeshousestrong_housesandgeneralconstructionmaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildahousekeypartsofhouse',
            name='bad_photo',
            field=models.ImageField(blank=True, null=True, upload_to='HousesAndGeneralConstruction/KeyPartsOfHouse/bad_photo/'),
        ),
        migrations.AlterField(
            model_name='buildahousekeypartsofhouse',
            name='good_photo',
            field=models.ImageField(blank=True, null=True, upload_to='HousesAndGeneralConstruction/KeyPartsOfHouse/good_photo/'),
        ),
        migrations.AlterField(
            model_name='buildahousemakeshousestrong',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='HousesAndGeneralConstruction/BuildAHouseMakesHouseStrong/pdf/'),
        ),
    ]
