# Generated by Django 2.0 on 2018-11-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20181031_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildahousekeypartsofhouse',
            name='bad_photo_desc_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildahousekeypartsofhouse',
            name='bad_photo_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildahousekeypartsofhouse',
            name='good_photo_desc_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildahousekeypartsofhouse',
            name='good_photo_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildahousekeypartsofhouse',
            name='name_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buildahousekeypartsofhouse',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buildahousemakeshousestrong',
            name='name_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buildahousemakeshousestrong',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='housesandgeneralconstructionmaterials',
            name='bad_photo_desc_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housesandgeneralconstructionmaterials',
            name='bad_photo_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housesandgeneralconstructionmaterials',
            name='good_photo_desc_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housesandgeneralconstructionmaterials',
            name='good_photo_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housesandgeneralconstructionmaterials',
            name='name_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='housesandgeneralconstructionmaterials',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
