# Generated by Django 2.0 on 2018-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20181101_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardSchoolDesignPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='HousesAndGeneralConstruction/')),
            ],
        ),
    ]
