# Generated by Django 2.0 on 2018-11-12 06:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0059_constructionsteps_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('call_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_from_log', to=settings.AUTH_USER_MODEL)),
                ('call_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_to_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
