# Generated by Django 2.0 on 2018-11-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='substepchecklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
