# Generated by Django 2.0 on 2018-12-07 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20181114_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCommonSubStepChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('specification', models.TextField()),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_checklists', to='core.Site')),
                ('substep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_checklists', to='core.ConstructionSubSteps')),
            ],
        ),
        migrations.CreateModel(
            name='NewSubStepChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('common_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_checklists', to='core.NewCommonSubStepChecklist')),
            ],
        ),
        migrations.RemoveField(
            model_name='substepchecklist',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='substepchecklist',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='substepchecklist',
            name='text_de',
        ),
        migrations.RemoveField(
            model_name='substepchecklist',
            name='text_en',
        ),
    ]
