# Generated by Django 2.0 on 2018-12-09 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20181207_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcommonsubstepchecklist',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_checklists', to='core.SiteSteps'),
        ),
    ]
