# Generated by Django 2.0 on 2018-12-09 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_newcommonsubstepchecklist_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsubstepchecklist',
            name='common_checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_checklists', to='core.NewCommonSubStepChecklist'),
        ),
    ]
