# Generated by Django 2.0 on 2018-12-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20181209_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcommonsubstepchecklist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
