# Generated by Django 2.0 on 2018-12-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_newcommonsubstepchecklist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcommonsubstepchecklist',
            name='status',
        ),
        migrations.AddField(
            model_name='newsubstepchecklist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
