# Generated by Django 2.0 on 2018-12-11 06:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20181211_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.models.OverwriteStorage(), upload_to='materials/updated_bad_photo'),
        ),
        migrations.AlterField(
            model_name='constructionsteps',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=core.models.OverwriteStorage(), upload_to='construction_step/icons/'),
        ),
        migrations.AlterField(
            model_name='goodphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.models.OverwriteStorage(), upload_to='materials/updated_good_photo'),
        ),
    ]
