# Generated by Django 2.0 on 2018-12-20 06:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20181211_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsteps',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.models.OverwriteStorage(), upload_to='construction_step/'),
        ),
    ]
