# Generated by Django 2.0 on 2018-12-28 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0071_auto_20181220_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Responded')], default=0, max_length=50)),
                ('feedback', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_feedback', to='core.SubstepReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
