# Generated by Django 2.0 on 2018-12-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_reportfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfeedback',
            name='status',
        ),
        migrations.AddField(
            model_name='substepreport',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Responded'), ('2', 'Rejected')], default=0, max_length=50),
        ),
    ]
