# Generated by Django 2.0 on 2019-01-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20190107_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='bad_photo',
            field=models.ImageField(blank=True, null=True, upload_to='materials/bad_photo', verbose_name='Bad Photo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='good_photo',
            field=models.ImageField(blank=True, null=True, upload_to='materials/good_photo', verbose_name='Good Photo'),
        ),
    ]
