# Generated by Django 2.0 on 2019-01-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20190108_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='core.SubstepReport'),
        ),
    ]
