# Generated by Django 2.0 on 2019-01-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20190109_0929'),
        ('core', '0078_auto_20190109_1024'),
    ]

    operations = [
    ]
