# Generated by Django 2.0 on 2019-01-14 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20190111_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfeedback',
            name='report',
        ),
        migrations.AddField(
            model_name='sitereport',
            name='feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_feedback', to='core.ReportFeedback'),
        ),
        migrations.AddField(
            model_name='substepreport',
            name='feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substep_feedback', to='core.ReportFeedback'),
        ),
    ]
