# Generated by Django 2.0 on 2019-01-14 06:50

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20190114_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConstructionSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, storage=core.models.OverwriteStorage(), upload_to='construction_step/')),
                ('icon', models.ImageField(blank=True, null=True, storage=core.models.OverwriteStorage(), upload_to='construction_step/icons/')),
                ('order', models.IntegerField(default=0)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_steps', to='core.Site')),
            ],
        ),
    ]
