# Generated by Django 2.0 on 2019-01-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_siteconstructionsteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconstructionsteps',
            name='name_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='siteconstructionsteps',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
