# Generated by Django 2.0 on 2019-01-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20190114_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconstructionsteps',
            name='site',
        ),
        migrations.DeleteModel(
            name='SiteConstructionSteps',
        ),
    ]
