# Generated by Django 2.0 on 2019-01-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20190114_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcommonsubstepchecklist',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='newsubstepchecklist',
            options={'ordering': ('title',)},
        ),
    ]
