# Generated by Django 2.0 on 2019-02-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20190130_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substepreport',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
