# Generated by Django 2.0 on 2019-05-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_substepreport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='substepreport',
            name='type',
            field=models.CharField(choices=[(0, 'Urgent'), (1, 'Update'), (2, 'Alert')], default=0, max_length=100),
        ),
    ]
