# Generated by Django 2.0 on 2019-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_substepreport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitereport',
            name='category',
            field=models.CharField(choices=[(0, 'Progress update'), (1, 'Issues/Concerns'), (2, 'Questions/Inquiries')], default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='sitereport',
            name='type',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Update', 'Update'), ('Alert', 'Alert')], default=0, max_length=100),
        ),
    ]
