# Generated by Django 2.0 on 2019-05-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_substepreport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substepreport',
            name='type',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Update', 'Update'), ('Alert', 'Alert')], default=0, max_length=100),
        ),
    ]
