# Generated by Django 2.0 on 2019-06-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20190527_1112'),
        ('core', '0090_auto_20190528_0602'),
    ]

    operations = [
    ]
