# Generated by Django 2.0 on 2019-06-12 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_remove_sitereport_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/', verbose_name='Image')),
                ('sitereport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.SiteReport')),
            ],
        ),
    ]
