# Generated by Django 2.0 on 2019-07-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_siteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='substepreport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='substep_report_images', to='core.SubstepReport'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='sitereport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='siteimages', to='core.SiteReport'),
        ),
    ]
