"""
Django settings for survey project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')fr_ek(mgen5_r!ra-jv^rhxt^!5dh3051cmumhdm31e8lak0('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party apps
    'rest_framework',
    'phonenumber_field',
    'rest_framework.authtoken',
    'rest_framework_swagger',
    'mapwidgets',
    'import_export',
    'fcm_django',

    # local apps
    'core',
    'userrole',
    'webpack_loader',
    'modeltranslation',
    'django.contrib.gis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'userrole.middleware.RoleMiddleware',
]

ROOT_URLCONF = 'survey.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'core.context_processors.reports_list',
            ],
        },
    },
]

WSGI_APPLICATION = 'survey.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

FCM_DJANGO_SETTINGS = {
        "FCM_SERVER_KEY": "[AAAAErlWVmc:APA91bEu52IIQ3gpwWuihnwgLoKMqb-A9uHGgnUkzvjKysL5etBn9EW8l6k817jjqhbhUzRPzuHSua_sMA4bg8-D3h4gLCtQwmdRoIDFSijl8LbL3hKSk_w92_iTNqFobEf0ElClcgUx]"
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


gettext = lambda s: s
LANGUAGES = (
    ('de', gettext('German')),
    ('en', gettext('English')),
)
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
}

WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': False,
        'BUNDLE_DIR_NAME': '/dist/',#('/build/' if DEBUG else '/dist/'),
        # 'BUNDLE_DIR_NAME': '/build/',#('/build/' if DEBUG else '/dist/'),
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        # 'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats-local.json'),
    }
}

MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 8),
        ("mapCenterLocation", [12.8797, 121.7740]),
    ),
    "GOOGLE_MAP_API_KEY": "AIzaSyADDQuj6F2x8p1dEa_oSyinWepcGHrVxvU"
}

EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'puskarjoshi22@gmail.com'
EMAIL_HOST_PASSWORD = '********'
EMAIL_PORT = 587

FCM_DJANGO_SETTINGS = {
        "FCM_SERVER_KEY": "AAAAAWtWQfs:APA91bEpXDHToGF7COLM0MYc_W3hcHoncILGepywbnBLqgyQAbBSIWl_NpbRhoI5rnfhagoDNVnqOiKNESgjwY3JUNJxW7ncskJ91PPtBt25hWSGXpPz3GoFv47lwzQGEfBQ4LGjDM6-"
}

try:
    from .local_settings import *
except Exception as e:
    pass