# Generated by Django 2.0 on 2018-05-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to='auth.Group'),
        ),
    ]
