# Generated by Django 2.0 on 2018-05-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0002_auto_20180511_0431'),
        ('userrole', '0002_auto_20180509_0706'),
    ]

    operations = [
    ]
