# Generated by Django 2.0 on 2018-11-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0005_auto_20180924_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('userrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userrole.UserRole')),
                ('phone_number', models.CharField(blank=True, max_length=250)),
            ],
            bases=('userrole.userrole',),
        ),
    ]
