# Generated by Django 2.0 on 2019-01-10 10:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0006_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
