# Generated by Django 2.0 on 2019-06-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0007_userrole_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
